#!/bin/bash
REL="$(rpm -E %fedora)"
echo "We are running Fedora $REL."

install_suckless() {
    cd ~/.config/
    git clone https://github.com/freakMCD/dwm && cd dwm
    sudo make clean install
    cd ..
    git clone https://github.com/freakMCD/st && cd st
    sudo make clean install
}

setup_repos() {
    # RPMFusion
    sudo dnf install \
        https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-"$REL".noarch.rpm \
        https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$REL".noarch.rpm \

    sudo dnf copr enable tokariew/ueberzug
    sudo dnf update --refresh
}

install_basics() {
    # Multimedia codecs and printing packages
    sudo dnf install @multimedia @printing --exclude=qt5-qtwebengine-freeworld,pipewire-codec-aptx 

    # Basics
    sudo dnf install feh maim lftp xev xclip xprop xdotool\
    fd-find fzf mpd mpc mpv pass newsboat neomutt cyrus-sasl-plain neovim puddletag \
    ueberzug weechat zathura zathura-pdf-mupdf\
    gcc gdouros-symbola-fonts google-noto-cjk-fonts pavucontrol python3-pip python3-devel 

    lf-update   
}

install_python_packages() {
    echo "Installing streamlink, animdl, pywal, yt-dlp"
    pip install --user --upgrade streamlink
    pip install --user animdl
    pip3 install --user pywal
    python3 -m pip install -U yt-dlp
}

install_texlive_packages() {
    # texlive bits
    sudo dnf install texlive latexmk
}

enable_services () {
    echo "Starting/enabling mpd service"
    systemctl --user start mpd.service
    systemctl --user enable mpd.service  

    echo "Disabling cups, sshd services, dnf-makecache"
    systemctl disable --now dnf-makecache.timer
    systemctl disable --now cups.service
}

configure_neovim() {

}


usage() {
    echo "$0: Install packages and software"
    echo
    echo "Usage: $0 [-dbtpah]"
    echo
    echo "-d: Install dwm, st"
    echo "-b: install basics and Setup Repos"
    echo "-t: install TeXlive packages"
    echo "-p: install Python packages"
    echo "-a: do all of the above"
    echo "-h: print this usage text and exit"
}

if [ $# -lt 1 ]
then
    usage
    exit 1
fi

# parse options
while getopts "sbtah" OPTION
do
    case $OPTION in
        d)
            install_suckless
            exit 0
            ;;
        b)
            setup_repos
            install_basics
            configure_neovim
            enable_services
            exit 0
            ;;
        p)
            install_python_packages
            exit 0
            ;;            
        t)
            install_texlive_packages
            exit 0
            ;;
        a)
            setup_repos
            install_basics
            configure_neovim
            install_python_packages
            install_texlive_packages
            enable_services
            exit 0
            ;;
        h)
            usage
            exit 0
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done
