#default_provider: allanime
default_provider: animepahe
quality_string: best
default_player: mpv

players:
    mpv:
        executable: mpv
        opts: ['--no-terminal']

fzf:
    executable: fzf
    opts: []
    state: true

