# Shell variables
# Generated by 'wal'
wallpaper='/home/edwin/.config/wallpaper/crowmaskguy.jpg'

# Special
background='#050104'
foreground='#ccd5dc'
cursor='#ccd5dc'

# Colors
color0='#050104'
color1='#a73335'
color2='#2d6c89'
color3='#3a6fb3'
color4='#4a87b2'
color5='#43aec0'
color6='#6690bc'
color7='#ccd5dc'
color8='#8e959a'
color9='#b53335'
color10='#277396'
color11='#326ebb'
color12='#5195c5'
color13='#39b9ce'
color14='#6f9ecf'
color15='#ccd5dc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
